export default{
    SET_ACTIVE: 'SET_ACTIVE',
    CONNECT_API: 'CONNECT_API',
    DISCONNECT_API: 'DISCONNECT_API',
    UPDATE_BASE_URL: 'UPDATE_BASE_URL',
    SET_CONNECTING: 'SET_CONNECTING',
    SET_INFORMATION: 'SET_INFORMATION',
    SET_DEBUG: 'SET_DEBUG',
    SET_UPDATE: 'SET_UPDATE',
}
